# Generated by Django 5.0.2 on 2024-09-02 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='ImTooDumbForAsync', max_length=200)),
                ('is_online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('public_username', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('elo', models.IntegerField(default=1000)),
                ('current_match_id', models.CharField(default='0', max_length=200)),
                ('is_playing', models.BooleanField(default=False)),
                ('is_in_tournament', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(default='/mnt/c/Users/33662/Documents/42/projets42/ft_transcendence/transcendence/profile_image/willow.png', max_length=255, upload_to='images')),
                ('old_profile_picture_name', models.CharField(default='None')),
                ('profile_picture_full_name', models.CharField(default='willow.png', max_length=255)),
                ('games_played_ttt', models.IntegerField(default=0)),
                ('nb_win_ttt', models.IntegerField(default=0)),
                ('nb_lose_ttt', models.IntegerField(default=0)),
                ('nb_draw_ttt', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('last_ping', models.CharField(default='0', max_length=100)),
                ('games_played_pong', models.IntegerField(default=0)),
                ('nb_win_pong', models.IntegerField(default=0)),
                ('nb_lose_pong', models.IntegerField(default=0)),
                ('is_waiting', models.BooleanField(default=False)),
                ('alias_tournament', models.CharField(default='none', max_length=200)),
                ('nb_goal_scored', models.IntegerField(default=0)),
                ('nb_goal_scored_average', models.IntegerField(default=0)),
                ('nb_goal_taken', models.IntegerField(default=0)),
                ('nb_goal_taken_average', models.IntegerField(default=0)),
                ('nb_tournament_won', models.IntegerField(default=0)),
                ('nb_tournament_lost', models.IntegerField(default=0)),
                ('nb_tournament_played', models.IntegerField(default=0)),
                ('nb_match_rage_quit', models.IntegerField(default=0)),
                ('nb_tournament_rage_quit', models.IntegerField(default=0)),
                ('trust_factor', models.FloatField(default=100.0)),
                ('nb_tournament_rage_quit_admin', models.IntegerField(default=0)),
                ('friends', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PongMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(default='0', max_length=200, null=True)),
                ('date', models.CharField(default='42424242424242', max_length=200, null=True)),
                ('Player1_name', models.CharField(max_length=200, null=True)),
                ('Player2_name', models.CharField(max_length=200, null=True)),
                ('winner_score', models.IntegerField(default=0)),
                ('loser_score', models.IntegerField(default=0)),
                ('winner_name', models.CharField(default='None', max_length=200, null=True)),
                ('loser_name', models.CharField(default='None', max_length=200, null=True)),
                ('tournament_level', models.IntegerField(default=-1, null=True)),
                ('tournament_id', models.CharField(default='none', max_length=200, null=True)),
                ('tournament_match_id', models.IntegerField(default=-1, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('current_score_player_1', models.IntegerField(default=0)),
                ('current_score_player_2', models.IntegerField(default=0)),
                ('Loser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loser', to=settings.AUTH_USER_MODEL)),
                ('Player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Player1', to=settings.AUTH_USER_MODEL)),
                ('Player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Player2', to=settings.AUTH_USER_MODEL)),
                ('Winner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PongRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nb_user', models.IntegerField(default=0)),
                ('is_full', models.BooleanField(default=False)),
                ('match_id', models.CharField(max_length=200)),
                ('tournament_mode', models.BooleanField(default=False)),
                ('first_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.CharField(default='42424242424242', max_length=30)),
                ('board', models.CharField(default='000000000', max_length=10)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_ttt', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ttt', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_ttt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='LOL', max_length=200, unique=True)),
                ('is_running', models.BooleanField(default=False)),
                ('nb_player', models.IntegerField(default=1)),
                ('display_name', models.CharField(default='Tournament', max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('match', models.ManyToManyField(to='game.pongmatch')),
                ('player', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner_tournament', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TTTRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nb_user', models.IntegerField(default=0)),
                ('is_full', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
