services:
    database:
        image: postgresql
        build: 
            context: 
                DB/.
        expose: 
            - "5432"
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            interval: 10s
            timeout: 30s
            retries: 5
            start_period: 10s
        volumes:
          - DB:/var/lib/postgresql/data
    backend:
        image: backend
        build: .
        ports:
            - "8888:8888"
        env_file:
            - .env
        depends_on:
            database:
                condition: service_healthy
        volumes:   
          - wb:/home/volume/transcendance
        
volumes:
  wb:
  DB:
